---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    #  - import_tasks: chapter2/pam_pwquality.yml
    #  - import_tasks: chapter2/user_and_group.yml
    
