---
- name: Provision VM (Rocky Linux 9)
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  tasks:
    #  - import_tasks: chapter2/pam_pwquality.yml
    #  - import_tasks: chapter2/user_and_group.yml
    
